### ISSUE TITLE
Upper diacritic placement should be at the same height for all letters

### ISSUE THREAD

**Issue by NeilSureshPatel** [notofonts/nko#7]
### Title 
Upper diacritic placement should be at the same height for all letters
### Font 
NotoSansNKo-Regular.otf
NotoSansNKo-Regular.ttf

### Where the font came from, and when
  >   Site: https://cdn.jsdelivr.net/gh/notofonts/notofonts.github.io/fonts/NotoSansNKo/unhinted/otf/NotoSansNKo-Regular.otf
  >   Date: 2023-03-15 

### Font Version
Version 2.003

### Issue
Diacritics that are placed above letters should be all at the same height rather than varying in relative to the height of base letter. I double checked this with WODN just now. The anchors for the "x-height" letters need to be moved up to match the "cap-height" letters.

### Character data
U+07CB
U+07CD
U+07CE
U+07D8
U+07DB
U+07E8
U+07E9
U+07EA

### Screenshot
Incorrect:
![image](https://user-images.githubusercontent.com/46502494/225402881-f9c7d014-f617-4a9c-a4e6-e5b9098a84e0.png)

Correct:
![WhatsApp Image 2023-03-15 at 12 19 36](https://user-images.githubusercontent.com/46502494/225402134-b7395688-4db8-47bd-8a68-c8a11d945514.jpg)

Anchor positions in current Noto N'ko font:
<img width="143" alt="image" src="https://user-images.githubusercontent.com/46502494/225403591-1bdc1983-ce51-4cc4-81ff-6e873fd0b033.png">
<img width="229" alt="image" src="https://user-images.githubusercontent.com/46502494/225403633-10410797-c0e9-421b-8dd7-6ad9eee30bc3.png">

**Comment by r12a** [comment]
Thanks.  Now corrected at https://w3c.github.io/afrlreq/nko/index.html#context

Is there ever a situation where  ߳ [U+07F3 NKO COMBINING DOUBLE DOT ABOVE​] (used to represent foreign sounds like /y/, /ǝ/, and /ʕa/) are used in combination with a tone mark?  If so, how is the double-diacritic handled?

**Comment by simoncozens** [comment]
I've fixed all the above anchors to have a constant Y position.

![shape](https://user-images.githubusercontent.com/106728/236436093-a9f48496-bf32-4673-9329-373f4a4af332.png)
