### ISSUE TITLE
Design of tonal apostrophes are difficult to distinguish on low-res phones

### ISSUE THREAD

**Issue by NeilSureshPatel** [notofonts/nko#8]
Title
Design of tonal apostrophes are difficult to distinguish on low-res phones

Font
NotoSansNKo-Regular.otf
NotoSansNKo-Regular.ttf

Where the font came from, and when
Site: https://cdn.jsdelivr.net/gh/notofonts/notofonts.github.io/fonts/NotoSansNKo/unhinted/otf/NotoSansNKo-Regular.otf
Date: 2023-03-15

Font Version
Version 2.003

Issue
The design of the high and low tone apostrophes is difficult to differentiate on low-res phones that are common in Africa. At small point sizes the wedge style of the apostrophes in the current design appears the same. The preference is to use more of a curled shape that is easier to distinguish.

Character data
U+07F4
U+07F5

Screenshot

Current design: (07F4: right, 07F5: left)

<img width="243" alt="image" src="https://user-images.githubusercontent.com/46502494/226491425-b24d77a8-6d3b-4fa0-8c90-6bde05439e7e.png">

Preferred design: (07F4: right, 07F5: left)

<img width="259" alt="image" src="https://user-images.githubusercontent.com/46502494/226491512-3450981a-c58c-48f5-b5ef-9d78acbd9d02.png">

**Comment by simoncozens** [comment]
This is the same as #3.

**Comment by simoncozens** [comment]
Done, using the shape of the Arabic comma which was in the font.

![shape](https://user-images.githubusercontent.com/106728/236438490-29084c08-f938-45f7-aa88-3b81bbb2ea4f.png)

**Comment by simoncozens** [comment]
Meant to put that on #3, but never mind.
