### ISSUE TITLE
Unjoined font for N'Ko

### ISSUE THREAD

**Issue by r12a** [notofonts/nko#9]
Adlam comes with a joined and unjoined font.  N'Ko headings, titles, and other display text are also often written using a non-joining font.  Could Noto provide an NKo Unjoined font?

Here's an example:
![unjoined](https://user-images.githubusercontent.com/4839211/232869708-b3d7bcf5-d07f-405c-83b9-9d8e32abad13.png)

The example above shows an older-style font in the title that has baseline extensions for some letters (you can see [more examples](http://cormand.huma-num.fr/maninkabiblio/periodiques/silabosoona5.pdf)).   Although this is fairly common, apparently the World Organisation for the Development of N'Ko prefers that the letters just look like isolated forms of the current Noto Sans N'Ko font.

It is possible to use CSS to make a font show unjoined letters, if the OpenType features are available. Simply add something like this to your style sheet.

`.unjoined { font-feature-settings: "init" 0, "medi" 0, "fina" 0, "isol" 1; }`

But that's a little complicated for most people, and doesn't help those using Word, etc.

(Some further discussion can be found at https://github.com/w3c/afrlreq/issues/29) cc @NeilSureshPatel

**Comment by simoncozens** [comment]
> But that's a little complicated for most people, and doesn't help those using Word, etc.

It also sounds (from the linked issue and also [your page here](https://r12a.github.io/scripts/nkoo/nqo.html#noncursive)) that simply removing the positional features is not enough, but that some design adjustments would be needed. 

At the same time, it looks like it might be possible (at least for a first attempt) to use the .init forms in cases where a horizontal line at the bottom is needed. If that's all it would take, then I would be very happy to create an unjoined variant; it shouldn't be too hard. If on the other hand we're going to need to commission some design work, then I suspect it won't happen this year.

**Comment by NeilSureshPatel** [comment]
@simoncozens I have posted some additional clarifying notes on the W3C issues page. [https://github.com/w3c/afrlreq/issues/29](url) I think attempting to replicate the connecting stroke on some of the isolated forms would just be carrying over legacy font implementations. A good first pass would be to just use the .isol forms for an unconnected variant.

**Comment by simoncozens** [comment]
Thanks, Neil. I'll pull an unconnected variant together.

**Comment by r12a** [comment]
It occurred to me just now that these unjoined glyphs are generally used for headings, and have a bolder appearance than the surrounding text.  But Noto has no bold N'Ko font.  How easy would it be to add a bold font face, too?

**Comment by NeilSureshPatel** [comment]
> Thanks, Neil. I'll pull an unconnected variant together.

How hard would it be to fix the anchor positions [Issue #7](https://github.com/notofonts/nko/issues/7) and tone marks [Issue #3](https://github.com/notofonts/nko/issues/3), while you are in the font?

**Comment by simoncozens** [comment]
> How easy would it be to add a bold font face, too?

I did wonder if that might come up, and I agree it would be ideal. The problem is that I am not a designer. :-) OTOH it's a fairly simple monoline design, so you can get most of the way with an offset curve filter. The only awkward bits would be JONA JA and JONA CHA, and possibly OO DENNEN.

I would be happy to give it a try and then pass it over to a real designer for inspection and review.

**Comment by NeilSureshPatel** [comment]
> > How easy would it be to add a bold font face, too?
> 
> I did wonder if that might come up, and I agree it would be ideal. The problem is that I am not a designer. :-) OTOH it's a fairly simple monoline design, so you can get most of the way with an offset curve filter. The only awkward bits would be JONA JA and JONA CHA, and possibly OO DENNEN.
> 
> I would be happy to give it a try and then pass it over to a real designer for inspection and review.

I would gladly review a Bold design if you whip one up. It would definitely be nice to have. A bold connected font would be trickier since all the pinches in in the joining strokes would need to be adjusted. But a bold unconnected font would be a great place to start.

**Comment by simoncozens** [comment]
I've had a go at this. You can get the TTFs and proof files from [this actions link](https://github.com/notofonts/nko/actions/runs/4914985794). The regular is just the joined without positional features. The bold is offset stroke with some corrections, set slightly tighter.

**Comment by NeilSureshPatel** [comment]
Thanks @simoncozens. For the most part this is looking pretty good. There are few artifacts from the stroke offset that need to be tweaked, i.e. ink traps, minor stroke width adjustments and proportion adjustments. I can give a quick cleanup pass. Nothing too in depth since it's not a commission but enough to tidy things up.

**Comment by NeilSureshPatel** [comment]
@simoncozens just submitted a [PR](https://github.com/notofonts/nko/pull/10) for some tweaks I made to the unjoined source. The only thing I didn't touch is the dorome (07FE). I wanted to check on this before touching it since it would affect the joined font as well. As designed this glyph is very tall compared to the numbers. If you wanted to use the (07D8) as a component at full size I think it would be better to place it over the old ra (07EA) instead of the new one. This is an acceptable rendering of the form.

**Comment by simoncozens** [comment]
Thanks very much for this. Agree the dorome is misproportioned. Having it as JONA RA + DA would be easy (for both fonts), but I'll await your advice on whether it's the "best" approach.

**Comment by NeilSureshPatel** [comment]
I reviewed a bunch of N'ko legacy fonts and I see only one instance of joining the DA to the JONA RA, but even in this case the DA is re-proportioned. I think the approach is valid but if we have to change the proportions of the DA anyway it is same amount of the work to make it all fit above the baseline. I made the change to the Unjoined, [PR 11](https://github.com/notofonts/nko/pull/11), this can be ported over to the joined font.

**Comment by simoncozens** [comment]
Thanks to Neil, Noto Sans NKo Unjoined now exists, and can be downloaded from https://notofonts.github.io/nko/
There'll be an official release at the end of the quarter, at which point it should start making its way into distributions, etc.

**Comment by NeilSureshPatel** [comment]
Great! Thanks for working this in Simon!

**Comment by r12a** [comment]
Excellent news! Many thanks, Simon.
